version: "3.9"
services:
  reinforce:
    image: reinforce:latest
    build: ./reinforce.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]